#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'dmg'
cookbook 'homebrew',
  :git => 'https://github.com/patcon/chef-homebrew.git',
  :ref => 'detect-sudo-user'
cookbook 'pivotal_workstation',
  :git => 'https://github.com/pivotal/pivotal_workstation.git',
  :ref => 'master'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
