#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'dmg'
cookbook 'homebrew',
  :git => 'https://github.com/patcon/chef-homebrew.git',
  :ref => 'detect-sudo-user'
cookbook 'pivotal_workstation',
  :git => 'https://github.com/myplanet-experimental/pivotal_workstation.git',
  :ref => 'leverage-homebrew-cookbook'
cookbook 'zip_app'
