#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Pending PR: https://github.com/opscode-cookbooks/ark/pull/5
cookbook 'ark',
  :git => 'https://github.com/myplanetdigital/chef-ark.git',
  :ref => 'cherrypick-dirs'
cookbook 'dmg'
cookbook 'homebrew',
  :git => 'https://github.com/patcon/chef-homebrew.git',
  :ref => 'detect-sudo-user'
cookbook 'homesick'
cookbook 'pivotal_workstation',
  :git => 'https://github.com/myplanet-experimental/pivotal_workstation.git',
  :ref => 'leverage-homebrew-cookbook'
cookbook 'zip_app'
